name: 'CI Pipeline'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-data-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install and Configure uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        shell: bash
      - name: Create Virtual Environment
        run: uv venv
      - name: Install dependencies
        run: uv pip install -r requirements.txt
      - name: Run Data Pipeline
        run: uv run python sdp-data/pipeline.py
      - name: Upload Dataset Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdp-dataset
          path: sdp-data/dados_completos.csv
          if-no-files-found: error

  build-model-pipeline:
    needs: build-data-pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install and Configure uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        shell: bash
      - name: Create Virtual Environment
        run: uv venv
      - name: Install dependencies
        run: uv pip install -r requirements.txt
      - name: Download Dataset Artifact
        uses: actions/download-artifact@v4
        with:
          name: sdp-dataset
          path: sdp-data
      - name: Run Model Pipeline
        run: uv run python sdp-model/pipeline.py
      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdp-model
          path: |
            sdp-model/champion_model.pkl
            sdp-model/preprocessor.pkl
            sdp-model/model_results.json
          if-no-files-found: error

  test-service-pipeline:
    needs: build-model-pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install and Configure uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        shell: bash
      - name: Create Virtual Environment
        run: uv venv
      - name: Install dependencies
        run: uv pip install -r requirements.txt
      - name: Download Model Artifact
        uses: actions/download-artifact@v4
        with:
          name: sdp-model
          path: sdp-model
      - name: Run Service Unit Tests
        run: PYTHONPATH=sdp-service/src uv run python -m unittest discover sdp-service/tests

  generate-report-and-presentation:
    needs: test-service-pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install and Configure uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        shell: bash
      - name: Create Virtual Environment
        run: uv venv
      - name: Install dependencies
        run: uv pip install -r requirements.txt
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
      - name: Move Artifacts
        run: |
          mv artifacts/sdp-dataset/dados_completos.csv sdp-data/
          mv artifacts/sdp-model/* sdp-model/
      - name: Generate Report and Presentation Assets
        run: uv run python sdp-report/generate_report.py
      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra latexmk
      - name: Compile LaTeX Presentation
        run: latexmk -pdf presentation/presentation.tex -output-directory=presentation
      - name: Upload Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdp-report
          path: sdp-report/index.html
      - name: Upload Presentation Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdp-presentation
          path: presentation/presentation.pdf
